<article class="subtitle-row">
    <h2>Playing game...</h2>
    <?php if ($state['state'] === 'win'): ?>
    <article class="alert-spacing">
        <article class="alert game-alert">You Win!!</article>
    </article>
    <?php elseif ($state['state'] === 'lose'): ?>
    <article class="alert-spacing alert-spacing-error">
        <article class="alert game-alert">You Lose!!</article>
    </article>
    <?php endif; ?>
    <figure class="container-photo circle img_tic o"></figure>
    <figure class="container-photo circle img_tic x"></figure>
    <p class="dates">Time: <span class="time" id="time"><?= $match->game_clock ?> sec</span></p>
    <h3 class="relative-pos-game">
        <span class="points"><span class="nameuser">Player: <span class="usermoves moves"><?= $state['player_moves']['player'] ?></span></span></span><span class="points"><span class="computer">Computer: <span class="computermoves moves"><?= $state['player_moves']['ai'] ?></span></span></span>
    </h3>
</article>
<article class="container-row relative-pos-game">
    <article class="game" id="app">
        <article v-for="sq of squares" :key="sq.id" class="field"><button :id="sq.id" :disabled="sq.hasMove" class="btn img_tic" :class="sq.playerClass" @click.prevent="makeMove(sq.id)"></button></article>
    </article>
</article>
<script>
    const initial_moves = <?= json_encode(array_map(function ($x) {return $x->serialize();}, $moves)) ?>;
    const initial_turn = <?= $state['state'] === 'unfinished' ? 'true' : 'false' ?>;
</script>
<article class="container-row center form">
    <br>
</article>
<?php if ($state['state'] === 'win'): ?>
<article class="container-row center form">
    <article class="form-win">
        <form action="/highscore" method="POST" enctype="multipart/form-data">
            <label for="nickname">Enter your Nickname </label>
            <input id="nickname" type="text" name="nickname" placeholder="Nickname" required>
            <input type="submit" name="" id="" class="" value="Submit">
        </form>
        <article class="alert-spacing-error">
            <article class="alert"><span class="underline">Message:</span> Enter your nickname !!</article>
        </article>
    </article>
    <br>
</article>
<?php endif; ?>
<div class="button-start">
    <a href="/reset"><button>START NEW GAME</button></a>
</div>