<article class="subtitle-row">
    <h2>Start new game</h2>
</article>
<article class="container-row form">
    <form class="form-content" action="/upload" method="POST" enctype="multipart/form-data">
        <?php if (!$user->avatar_set): ?>
        <label for="photo">Upload photo <span class="optional right"> Optional </span></label>
        <input id="photo" type="file" name="photo" accept="image/jpeg"><br>
        <?php endif; ?>
        <input type="submit" name="" id="" value="START NEW GAME">
    </form>
    <?php if (!empty($variables['image_error'])): ?>
    <article class="alert-spacing-error">
        <article class="alert"><span class="underline">Error uploading photo:</span> Verify size or type of file!!</article>
    </article>
    <?php endif; ?>
</article>
