<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TIC-TAC-TOE</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <style type="text/css">
        /* style for user image (overwrite .o) */
        .o {
            <?php

            if ($user->avatar_set) {
                $image = $user->uniqid;
            } else {
                $image = 'photo';
            }

            ?>
            background: url(<?= $user->getAvatar() ?>) no-repeat center center !important;
            background-size: 60px !important;
            border-radius: 50%;
            border: 1px solid rgba(0, 0, 0, .2) !important;
        }
    </style>
    <!-- put any js-code into this file -->
    <script src="assets/js/jquery-2.1.1.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>
<body>
<section class="container-game">
    <article class="title-row">
        <h1>TIC-TAC-TOE</h1>
    </article>
    <article class="row initial-page">
        <article class="col">
            <article class="subtitle-row">
                <h2>Instructions</h2>
            </article>
            <article class="container-row">
                Instructions of game:
                <ul>
                    <li>Select Photo (optional)</li>
                    <li>Press "Start New Game"</li>
                    <li>Play Game: try to mark three fields in a vertical, horizontal or diagonal row one move before the computer</li>
                </ul>
            </article>
            <article class="subtitle-row">
                <h2>High Scores</h2>
            </article>
            <article class="container-row high scroll">
                <article class="scroll-view">
                    <?php foreach ($scores as $score): ?>
                        <article class="score">
                            <h4 class="pos"<?php if ($score->avatar_set): ?> style="background: url(<?= $score->getAvatar() ?>)no-repeat center center;background-size: cover"<?php endif; ?>><?= $score->position ?></h4><h4 class="name-high"><?= $score->nickname ?> <span class="moves"><span><?= $score->score ?></span>-<span><?= $score->score - 1 ?></span></span></h4>
                            <p><span class="date-high"><?= $score->date ?></span><span class="time-high"><?= $score->game_clock ?> sec</span></p>
                        </article>
                    <?php endforeach; ?>
                </article>
            </article>
        </article>
        <article class="col border-line col-game-spacing">