<article class="subtitle-row">
    <h2>Start new game</h2>
</article>
<article class="container-row form">
    <form  class="form-content" action="" method="POST" enctype="multipart/form-data">
        <label for="photo">Upload photo <span class="optional right"> Optional </span></label>
        <input id="photo" type="file" name="photo"><br>
        <input type="submit" name="start" id="" value="START NEW GAME">
    </form>
    <?php if (!$upload_ok): ?>
    <article class="alert-spacing-error">
        <article class="alert"><span class="underline">Error uploading photo:</span> Verify size or type of file!!</article>
    </article>
    <?php endif; ?>
</article>